### PR TITLE
Upgrade to new VoodooRMI & VoodooPS2Controller

### PR DESCRIPTION
**Pull request by EETagent**

### CODE REVIEW

**Comment by khokho** [comment]
I believe gestures a bit worse on this branch. I've had trouble with 4 finger gestures when fingers are too close. Which master branch has no issue with. Maybe others can confirm.

**Comment by khokho** [comment]
There is difference for sure. But increasing sensitivity in bettertouchtool made it just as good.

**Comment by EETagent** [comment]
> I believe gestures a bit worse on this branch. I've had trouble with 4 finger gestures when fingers are too close. Which master branch has no issue with. Maybe others can confirm.

It might be related to this new option VoodooRMI config
```
<key>FingerMajorMinorDiffMax</key>
<integer>3</integer>
```

**Comment by khokho** [comment]
Turns out it was this change I had an issue with. I use gestures for swiping between full screen apps so swipe, write message, swipe back was not working for me because typing disabled touchpad.
```
  <key>DisableWhileTypingTimeout</key>
- <integer>100</integer>
+ <integer>2000</integer>
```

**Comment by EETagent** [comment]
I will set it to same value as before. 2s is too long delay

**Comment by khokho** [comment]
touchpad still got disabled after sleep today.

**Comment by EETagent** [comment]
> touchpad still got disabled after sleep today.

Well, that's bad. It's weird that we are probably only ones affected by this problem. I will sometime try to gather some kernel logs and open an issue on VoodooRMI GitHub

**Comment by EETagent** [comment]
As this issue exists even on current version, I won't delay merge because of it

**Pull request merged**
