### PR TITLE
Broadcom Wifi and Bluetooth Fix

### PR DESCRIPTION
**Pull request by currowth**
I replaced the stock intel wifi card with a broadcom bcm4352. I had to add the new kext to get bluetooth and wifi to work. They are both working perfectly.

### CODE REVIEW

**Comment by EETagent** [comment]
Thanks for your pull request and interest. Right now I have added support for the Intel Wifi card. I'm trying to create this EFI without hardware changes. However, I can create a Broadcom branch after the conflicts are resolved.

BTW, How does this EFI work on your machine? Are there any unknown problems?

**Comment by currowth** [comment]
The only issue i found is that, sometimes the bootmenu sound crackles. Other than that it works perfectly fine.

**Comment by EETagent** [comment]
If you mean that boot chime sometimes plays like for 0.2 seconds and than it stops.
It could be caused by

1. OpenCore update
2. Config.plist settings which enables OpenCore boot entry in T480's boot menu

**Comment by EETagent** [comment]
As this repository is targeted for machines equipped with Intel Wi-FI / Bluetooth, this would not be merged. Users running macOS on PC shall have some basic knowledge about it so for someone who already bought Broadcom card it should not be problem changing few kexts and small edits of config.plist.

Thanks for your effort.

**Pull request closed without merging**
