### PR TITLE
Added VoodooSMBus

### LINKED ISSUE #2: Add VoodooSMBus Maybe?
Hello, 
I'm super new to hackintosh but I somehow managed to boot it up on my t480. I found you repo a bit too late but it's really a blessing. 💯 👍 
I found this kext: https://github.com/VoodooSMBus/VoodooSMBus which I tried to install but could figure out the .patch files and messed up the boot. So I'm just suggesting you to maybe try it.

### PR DESCRIPTION
**Pull request by khokho**
I'm not a reliable person please check before merging 🤷 
resolves #2
The issue I was talking about was not fixed but the gestures do seem to work better.

### CODE REVIEW

**Comment by khokho** [comment]
kext is the one you provided in #2

**Comment by EETagent** [comment]
@khokho  From what I see, you did not add kext to the config.plist. Use ProperTree OC snapshot for that. It can not work, probably placebo effect. [Listed patches](https://github.com/VoodooSMBus/VoodooSMBus) should be applied too

**Comment by khokho** [comment]
oh I don't know how but I didn't commit config.plist
wait a sec.

**Comment by khokho** [comment]
I modified the first patch because opencore needs find and replace strings to be the same. 
Used this as a reference:
https://github.com/VoodooSMBus/VoodooSMBus/issues/20#issuecomment-560507543

**Comment by EETagent** [comment]
I would test it tomorrow. Does 4 fingers gestures works?

**Comment by khokho** [comment]
Yes it works. But I have big fingers so it's not so practical for me 😆

**Comment by EETagent** [comment]
@khokho In SSDT-KBRD-TP.aml there is TouchPad and TrackPoint patch which enables scrolling with TrackPoint and modifies TouchPad behaviour. Try removing it, I don't know if it's necessary for VoodooSMBus

**Comment by EETagent** [comment]
@khokho  Driver is not working, I did not see any progress with TouchPad behaviour.
To make sure my guess is true, I checked VoodooSMBus settings.

Snímek obrazovky 2020-06-10 v 8 47 28

The TouchPad should be of when the TrackPoint is used and 500 milliseconds later. But that is not happening. I can use both TrackPoint and TouchPad at the same time ( TP SSDT disabled )

**Comment by EETagent** [comment]
@khokho I don't think these patches are OC compatible, maybe we should ask [there](https://github.com/VoodooSMBus/VoodooSMBus/issues/20#issuecomment-560507543).

**Comment by EETagent** [comment]
https://github.com/EETagent/T480-OpenCore-Hackintosh/tree/testing

**Pull request closed without merging**
